# Copyright © 2025 Devin B. Royal.
# All Rights Reserved.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unified-mdm-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unified-mdm
  template:
    metadata:
      labels:
        app: unified-mdm
    spec:
      containers:
        - name: mdm
          image: unified-mdm-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /opt/mdm/resources
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: mdm-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: unified-mdm-service
spec:
  type: NodePort
  selector:
    app: unified-mdm
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
